### ISSUE TITLE
Composer problem OSX

### ISSUE THREAD

**Issue by bluedogmilan** [yooper/php-text-analysis#13]
Hi Yooper.
I tried to install the library on OSX but i got this error:

`composer require yooper/php-text-analysis
Using version ^1.0 for yooper/php-text-analysis
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yooper/php-text-analysis ^1.0 -> satisfiable by yooper/php-text-analysis[v1.0].
    - yooper/php-text-analysis v1.0 requires yooper/stop-words dev-master -> satisfiable by yooper/stop-words[dev-master] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.
`
--bd

**Comment by bluedogmilan** [comment]
same result on the dev machine (Debian)

**Comment by thinkspill** [comment]
By default, composer will only install `stable` packages. `yooper/stop-words` appears to only have a `dev` package.

https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by bluedogmilan** [comment]
Solved by manually adding "minimum-stability": "dev" in /composer.json

**Comment by yooper** [comment]
Based on the feed back in this ticket, the latest commit now uses stopwords 1.0, instead of dev-master. 

Thank you,
