### ISSUE TITLE
Best sentence of a long text

### ISSUE THREAD

**Issue by karam89** [yooper/php-text-analysis#25]
Hello:

It's really a great job, having neat code, and good implementation

I've one question:
Is there a way to get the best sentence of a given long text? (to be put as a short description of the text)
- Limited by max words count

Thanks in advanced

**Comment by yooper** [comment]
My approach would be:

1. Use the Rake algorithm in this library to find the top keywords
2. Use the sentence tokenizer to break up the text
3. Using the keywords extracted from the text using the Rake algorithm, find which sentence(s) have the most keywords in them.
4. Select the best sentence from the set of candidate sentences
