### ISSUE TITLE
what methods do you recommend for a simple Q&A bot?

### ISSUE THREAD

**Issue by mrmrn** [yooper/php-text-analysis#26]
I have a bunch of question and answer as a data-set. I want to develop a simple question answering bot by using this code.
The scenario is when a user ask a new question, the bot finds the most similar ask in the data-set and returns the relative answer to that ask.
I think to do this I must go through this steps:
1-normalizing the data-set questions by performing preprocessing
2-normalizing users new question
3-tokenizing users new question
4-using a stemmer(I dont know how?) on the step 3`s tokens
5-using cosine similarity.

what do you prefer for a bot like this?

**Comment by yooper** [comment]
This issue seems specific to implementing a QA bot. Try connecting with a developer who builds bots. I am not familiar with how they are made. 

Thank you,
