### ISSUE TITLE
PHPNGrams library

### ISSUE THREAD

**Issue by drupol** [yooper/php-text-analysis#28]
Hello,

I just published a [library PHPNgrams](https://github.com/drupol/phpngrams) and a colleague of mine just pointed me this project that I wasn't aware of.
It's very nice !

If you think PHPNgrams might be useful for you, let me know :)

Keep up the good work !

**Comment by yooper** [comment]
Thank you for contacting me. Great job on the PHPNgrams library. It is amazing to see 100% test coverage. Let me know if you are interested in somehow adding or integrating your library in with PHP Text Analysis library. 

Cheers,
