### ISSUE TITLE
Matching a phrase in text

### ISSUE THREAD

**Issue by LunarDevelopment** [yooper/php-text-analysis#33]
Hello! 

Being totally new to the complexities of text analysis it's been interesting getting to grips with your library. 

Something I've found tricky is a middle ground between an array of individual word array outputs like `getKeyValuesByWeight()` and the phrase outputs of `getKeywordScores()`  

If I have a keyword to check in a text, e.g. "search engine optimization", it doesn't appear as a key in the output of `getKeywordScores()` (although the phrase does appear multiple times in the text).

Is there a solution using this library you can suggest ?

**Comment by yooper** [comment]
```php
// method 1
// tokenize the text 
$tokens = normalize_tokens( tokenize($text));
// create the ngrams, you want "search engine optimization", set the 2nd parameter to 3
$ngrams = ngrams($tokens, 3);
$valuesByWeight = freq_dist($ngrams)->getKeywordScores();

// method 2, returns an array of positions the phrase was found at
$positions = text($text)->findAll("search engine optimization");
```

**Comment by LunarDevelopment** [comment]
Thank you for helping me, would the following code (when the NGRAM_SIZE is set to 3 ) be the same as your method 1 ?

```php 
        $tokens = (new WhitespaceTokenizer())->tokenize($content);
        $tokenDoc = new TokensDocument(array_map('strval', $tokens));
        $rake = new Rake($tokenDoc, self::NGRAM_SIZE);
        return $rake->getKeywordScores();
```

**Comment by yooper** [comment]
Yes, that approach is similar to method 1. Rake is used to get the keywords from a text, where method 1 just finds all the frequencies of the ngrams. A more comprehensive example of using the Rake algorithm can be found here. 

https://github.com/yooper/php-text-analysis/blob/master/tests/TextAnalysis/Analysis/Keywords/RakeTest.php
