### ISSUE TITLE
Find most similar

### ISSUE THREAD

**Issue by it-is-hacker-time** [yooper/php-text-analysis#34]
What algoritm should I use to find the closest match from a string to a set of strings.

Example of known inputs:
```
I would like a cheese pizza
I would like a cheese pizza with onions
I would like a cheese pizza without onions
```

Input I wanna match up and find most similiar, in case there are any similar (in this example there are just spelling mistakes):
```
I would like a ceese pizza with out onnions.
```

**Comment by yooper** [comment]
I recommend using the cosine similarity algorithm. 

```php
$text = []
$text[] = tokenize("I would like a cheese pizza");
$text[] = tokenize("I would like a cheese pizza with onions");
$text[] = tokenize("I would like a cheese pizza without onions");
$compareAgainst = tokenize("I would like a ceese pizza with out onnions.")
$bestScore = 0;
$bestIdx = 0;    
        $compare = new CosineSimilarityComparison();
        foreach($text as $index => $t)
        {
             $score = $compare->similarity($t, $compareAgainst);
             if($score > $best) {
                 $best = $score;
                 $bestIdx = $index;
            }
        }

echo "best match {$text[$bestIdx]}";

```

**Comment by tematres** [comment]
The same code with some corrections:

`require_once('vendor/autoload.php');

use TextAnalysis\Comparisons\CosineSimilarityComparison;

$text = [];
$text[]= "I would like a cheese pizza";
$text[] = "I would like a cheese pizza with onions";
$text[] = "I would like a cheese pizza without onions";

$compareAgainst = tokenize("I would like a ceese pizza with out onnions.");

//$bestScore = 0;
$best = 0;
$bestIdx = 0;    
        $compare = new CosineSimilarityComparison();


        foreach($text as $index => $t)
        {
        	$t=tokenize($t);
             $score = $compare->similarity($t, $compareAgainst);
             if($score > $best) {
                 $best = $score;
                 $bestIdx = $index;
            }
            
        }

echo "best match {$text[$bestIdx]}";
`
