### ISSUE TITLE
Unable to install | Neither Using Shared Hosting Nor Local Host

### ISSUE THREAD

**Issue by DevFranzBeta** [yooper/php-text-analysis#35]
hello, thanks for the text analyzer but I'm unable to install it.
I'm using a shared hosting which accepts PHP 5. 

I tried pasting the files in my server but it is not working.
 
For example, I've tried Email filter but it was not finding  "` ITokenTransformation` " from : 

`class EmailFilter implements ITokenTransformation`

the "`use TextAnalysis\Interfaces\ITokenTransformation;`" return an error too

Thanks, 
Franz [onlinefranztech@gmail.com]

**Comment by mferrara** [comment]
Franz,

Since you pasted the files on your server your application is likely not autoloading the classes from the package. You likely need to include the packages classes.

**Comment by DevFranzBeta** [comment]
Thanks very much, I'm a PHP noob but I simply removed the namespace and I used to Test : 

 ```
$filter = new EmailFilter();  
$word = "Thanks yooper here is my email : onlinefranztech@gmail.com";      
$output =  $filter->transform($word );
 echo  $output;
```
Output : 

> Thanks yooper here is my email : 

Problem needly solved! 👍

**Comment by yooper** [comment]
Thank you @mferrara  for helping!
