### ISSUE TITLE
starting with documentation

### ISSUE THREAD

**Issue by matthewstokeley** [yooper/php-text-analysis#43]
Hey, do you have a readme or a walkthrough for getting started with helping to write documentation?

**Comment by yooper** [comment]
Hello, 
There is no howto write documentation for this project. If you want to contribute checkout:

- https://github.com/yooper/php-text-analysis/wiki
- https://github.com/yooper/php-text-analysis-book

I am not sure what type of documentation you are interested in writing. Any contributions such as tutorials, examples or a quick start guide would be appreciated. Is there something specific you want to work on?

Thanks,

**Comment by matthewstokeley** [comment]
Nothing in particular.  NLP is a lot of fun and I thought I'd help out if I could. I'll think about it and let you know.
