### ISSUE TITLE
UTF8 for normalize_tokens

### ISSUE THREAD

**Issue by theDanielo** [yooper/php-text-analysis#55]
I modify the helpers.php file with small changes so it supports UTF8, I use the project for analysing norwegian text and this was important for my project
Thanks for so nice library ;)

function normalize_tokens( array $tokens, $normalizer = 'mb_strtolower' ): array {
        mb_internal_encoding('UTF-8');
	return array_map( $normalizer, $tokens );
}

**Comment by yooper** [comment]
Thanks. Let me know if you have any questions.
