### ISSUE TITLE
Entity Extraction returns empty array

### ISSUE THREAD

**Issue by Zera97** [yooper/php-text-analysis#56]
Hey,

i've started working with your wrapper for the "Stanford Named Entity Extraction", but all i get returned is an empty array. Also there are no error messages.

This is my Code:

```
            use TextAnalysis\Taggers\StanfordNerTagger;
            use TextAnalysis\Tokenizers\WhitespaceTokenizer;

            $jarpath = [HIDDEN]/stanford-yooper/stanford-ner.jar";
            $classifierPath =[HIDDEN]/stanford-yooper/classifiers/english.all.3class.distsim.crf.ser.gz";
     
            $engText = "Marquette County is a county located in the Upper Peninsula of the US state of Michigan. As of the 2010 census, the population was 67,077.";
            
            $document = new TokensDocument((new WhitespaceTokenizer())->tokenize($engText));
            $tagger = new StanfordNerTagger($jarpath,$classifierPath);
            $output = $tagger->tag($document->getDocumentData());
            var_dump($output); //empty Array

```

**Comment by yooper** [comment]
@Zera97 ,
Check out the wiki article https://github.com/yooper/php-text-analysis/wiki/Entity-Extraction-with-PHP

**Comment by Zera97** [comment]
Thank you for your Response!

I installed the jar and classifier manually according to the Wiki, since i couldnt figure out, how to use the command. I also tested the jar with the shell which was working.

If you could give me a some advice on how to use the shell command, i would try to install the NER files this way.

**Comment by yooper** [comment]
@Zera97 , I will reach out to you later today with a write up, on how to make it work.

Cheers,

**Comment by jmichaelterenin** [comment]
I'm about to install the jar and classifier manually myself, according to the Wiki. is there something additional I will need to know? : )
