### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by repat** [yooper/php-text-analysis#61]
* PHP Version: 7.4.2
* File: `vendor/yooper/php-text-analysis/src/Sentiment/Vader.php`, line 419

* Code:

```php
foreach($rows as $row)
{
    $this->lexicon[$row[0]] = $row[1];
}
```

* Problem: `$row` is not always an array

* Temp Fix:
```php
foreach($rows as $row)
{
    if(is_array($row)) {
      $this->lexicon[$row[0]] = $row[1];
    }
}
```

**Comment by yooper** [comment]
@repat , sorry for taking so long to get back to you. Thank you for you contribution!

**Comment by repat** [comment]
Could you also release a new version (1.5.5) please :-)

**Comment by yooper** [comment]
@repat , created release 1.5.5
